name: Release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        required: true
        description: Bump version number    
        options: [major, minor, patch]
        default: patch
  push:
    branches: [master]
  pull_request:
    types: 
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
jobs:
  bump:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: |
          git config --global user.name Olivaw[bot]
          git config --global user.email 64868532+iterative-olivaw@users.noreply.github.com
          git checkout -b bump/$(npm version ${{ github.event.inputs.bump }})
          git push --set-upstream origin --follow-tags $_
          gh pr create --title "Bump version to ${_##*/}" --fill
          gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$event"
        env:
          event: ${{ toJson(github.event) }}
  release:
    if: github.event_name == 'invalid' #github.event.pull_request.merged #&& startsWith(github.event.pull_request.head.ref, 'bump/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "$js" && false
        env:
          js: ${{ toJSON(github.event) }}
      - run: >-
          gh release create
          --target=${GITHUB_REF##*/}
          --title="CML ${GITHUB_REF##*/}
          --generate-notes
          # --draft
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
