name: Release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        required: true
        description: Bump version number    
        options: [major, minor, patch]
        default: patch
  pull_request:
    types: [closed]
jobs:
  bump:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name Olivaw[bot]
          git config --global user.email olivaw@iterative.ai
          git checkout -b bump/$(npm version ${{ github.event.inputs.bump }})
          git push --set-upstream origin --follow-tags $_
          gh pr create --title "Bump to ${_##*/}" --fill
          gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{github.token }}
  release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'refs/heads/bump/')
    runs-on: ubuntu-latest
    steps:
      - run: >-
          gh release create
          --target=${GITHUB_REF##*/}
          --title="CML ${GITHUB_REF##*/}
          --generate-notes
          # --draft
        env:
          GITHUB_TOKEN: ${{github.token }}
