name: Release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        required: true
        description: Bump version number    
        options: [major, minor, patch]
        default: patch
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name Olivaw[bot]
          git config --global user.email 64868532+iterative-olivaw@users.noreply.github.com
          git checkout -b bump/$(npm version ${{ github.event.inputs.bump }})
          git push --set-upstream origin --follow-tags HEAD
          gh pr create --title "Bump version to $(git describe --tags)" --fill
          gh pr merge --merge --admin
          gh release create --generate-notes --draft {--target=,--title=CML\ }$(git describe --tags)
        env:
          GITHUB_TOKEN: ${{ github.token }}


